Description:  This template contains all the necessary networking components/infrastructure to make the web app 
              Highly available, scalable, efficient and secure.

Parameters:
  VPC-WebApp:
    Description: The web app VPC.
    Type: String
  PublicSubnet1Cidr-WebApp:
    Description: The web app - Public Subnet 1 CIDR
    Type: String
  PublicSubnet2Cidr-WebApp:
    Description: The web app - Public Subnet 2 CIDR
    Type: String
  PrivateSubnet1Cidr-WebApp:
    Description: The web app - Private Subnet 1 CIDR
    Type: String
  PrivateSubnet2Cidr-WebApp:
    Description: The web app - Private Subnet 2 CIDR
    Type: String
  AZ1-WebApp:
    Description: The web app - Availibility Zone 1
    Type: String
  AZ2-WebApp:
    Description: The web app - Availibility Zone 2
    Type: String

WebApp-VPC:
  Type: AWS::EC2::VPC
  Properties: 
    CidrBlock: !Ref VPC-WebApp
    EnableDnsHostnames: true
    EnableDnsSupport: true
    Tags: 
      - Key: VPC
      - Value: VPC - high availibility web application
