Description:  This template contains all the necessary networking components/infrastructure to make the web app 
              Highly available, scalable, efficient and secure.

Parameters:
  VPC-WebApp:
    Description: The web app VPC.
    Type: String
  PublicSubnet1Cidr-WebApp:
    Description: The web app - Public Subnet 1 CIDR
    Type: String
  PublicSubnet2Cidr-WebApp:
    Description: The web app - Public Subnet 2 CIDR
    Type: String
  PrivateSubnet1Cidr-WebApp:
    Description: The web app - Private Subnet 1 CIDR
    Type: String
  PrivateSubnet2Cidr-WebApp:
    Description: The web app - Private Subnet 2 CIDR
    Type: String
  AZ1-WebApp:
    Description: The web app - Availibility Zone 1
    Type: String
  AZ2-WebApp:
    Description: The web app - Availibility Zone 2
    Type: String
  PublicRouteCidr-WebApp:
    Description: The web app - Public Route CIDR
    Type: String

WebApp-VPC:
  Type: AWS::EC2::VPC
  Properties: 
    CidrBlock: !Ref VPC-WebApp
    EnableDnsHostnames: true
    EnableDnsSupport: true
    Tags: 
      - Key: VPC
      - Value: VPC - high availibility web application

WebApp-PublicSubnet1:
  Type: AWS::EC2::Subnet
  Properties: 
    AvailabilityZone: !Ref AZ1-WebApp
    CidrBlock: !Ref PublicSubnet1Cidr-WebApp
    Tags: 
      - Key: Public Subnet 1
      - Value: Public Subnet 1 - high availibility web application
    VpcId: !Ref WebApp-VPC

WebApp-PublicSubnet2:
  Type: AWS::EC2::Subnet
  Properties: 
    AvailabilityZone: !Ref AZ2-WebApp
    CidrBlock: !Ref PublicSubnet2Cidr-WebApp
    Tags: 
      - Key: Public Subnet 2
      - Value: Public Subnet 2 - high availibility web application
    VpcId: !Ref WebApp-VPC

WebApp-PrivateSubnet1:
  Type: AWS::EC2::Subnet
  Properties: 
    AvailabilityZone: !Ref AZ1-WebApp
    CidrBlock: !Ref PrivateSubnet1Cidr-WebApp
    Tags: 
      - Key: Private Subnet 1
      - Value: Private Subnet 1 - high availibility web application
    VpcId: !Ref WebApp-VPC

WebApp-PrivateSubnet2:
  Type: AWS::EC2::Subnet
  Properties: 
    AvailabilityZone: !Ref AZ2-WebApp
    CidrBlock: !Ref PrivateSubnet2Cidr-WebApp
    Tags: 
      - Key: Private Subnet 2
      - Value: Private Subnet 2 - high availibility web application
    VpcId: !Ref WebApp-VPC

WebApp-InternetGateway:
  Type: AWS::EC2::InternetGateway
  Properties: 
    Tags: 
      - Key: Internet Gateway
      - Value: Internet Gateway - high availibility web application

WebApp-InternetgatewayAttachment:
  Type: AWS::EC2::VPCGatewayAttachment
  Properties: 
    InternetGatewayId: !Ref WebApp-InternetGateway
    VpcId: !Ref WebApp-VPC

WebApp-NatGatewayElasticIP1:
  Type: AWS::EC2::EIP
  DependsOn: WebApp-InternetgatewayAttachment
  Properties: 
    Domain: vpc
    Tags: 
      - Key: NatGateway Elastic IP1
      - Value: NatGateway Elastic IP1 - high availibility web application

WebApp-NatGatewayElasticIP2:
  Type: AWS::EC2::EIP
  DependsOn: WebApp-InternetgatewayAttachment
  Properties: 
    Domain: vpc
    Tags: 
      - Key: NatGateway Elastic IP2
      - Value: NatGateway Elastic IP2 - high availibility web application

WebApp-NatGateway1:
  Type: AWS::EC2::NatGateway
  Properties: 
    AllocationId: !GetAtt WebApp-NatGatewayElasticIP1.AllocationId
    SubnetId: !Ref WebApp-PublicSubnet1
    Tags: 
      - Key: Nat Gateway 1
      - Value: Nat Gateway 1 - high availibility web application

WebApp-NatGateway2:
  Type: AWS::EC2::NatGateway
  Properties: 
    AllocationId: !GetAtt WebApp-NatGatewayElasticIP2.AllocationId
    SubnetId: !Ref WebApp-PublicSubnet2
    Tags: 
      - Key: Nat Gateway 2
      - Value: Nat Gateway 2 - high availibility web application

WebApp-PublicRouteTable:
  Type: AWS::EC2::RouteTable
  Properties: 
    Tags: 
      - Key: Route Table
      - Value: Route Table - high availibility web application
    VpcId: !Ref WebApp-VPC

WebApp-PublicRoute:
  Type: AWS::EC2::Route
  Properties: 
    DestinationCidrBlock: !Ref PublicRouteCidr-WebApp
    GatewayId: !Ref WebApp-InternetGateway
    RouteTableId: !Ref WebApp-PublicRouteTable
